---
- name: Verify
  hosts: all
  gather_facts: yes
  tasks:

  - name: Ensure borg is executable
    command: borg --version
    register: borg_version
    changed_when: false

  - name: Extract borg package version
    set_fact:
      borg_version_cleaned: "{{ borg_version.stdout | regex_replace('[^0-9.-]', '') }}"

  - name: Query for latest version url
    ansible.builtin.uri:
      url: "https://github.com/borgbackup/borg/releases/latest"
      method: GET
      follow_redirects: none
      status_code: 302
    register: borg_latest_redirect_url

  - name: Extract latest borg release version
    ansible.builtin.set_fact:
      borg_latest_version: "{{ borg_latest_redirect_url.location | urlsplit('path') | regex_replace('.*/', '') }}"

  - name: Ensure borg version matches required
    fail:
      msg: "Expected version '{{ borg_latest_version }}' but found '{{ borg_version }}'!"
    when:
      - "borg_version_cleaned != borg_latest_version"
