
borg:
  install: pipx
  pipx_path: /usr/bin/pipx
  dependencies:
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python3-pkgconfig
    - libacl1-dev
    - libacl1
    - libssl-dev
    - liblz4-dev
    - libzstd-dev
    - libxxhash-dev
    - build-essential
    - pkg-config
    - libfuse-dev
    - libfuse3-dev
    - fuse3

pipx:
  install:
    archive:
      default: "1.8.0"
      versions:
        - version: "1.8.0"
          checksum: "sha256:b9eabd835dffe0677e36bd99416fc9837c592bd8c079235379bed3dfe043c601"
