---
- name: Verify
  hosts: all
  tasks:
  - name: Gather package facts
    package_facts:

  - name: Ensure borg is present
    fail:
      msg: "Expected to find package 'borg' in package list!"
    when:
      - "'borg' not in ansible_facts.packages"

  - name: Ensure borg is executable
    command: borg --version
    changed_when: false

  - name: Extract borg package version
    set_fact:
      borg_version: "{{ ansible_facts.packages['borg'][0].version }}"

  - name: Ensure borg version matches required
    fail:
      msg: "Expected version '{{ borg.version }}' but found '{{ borg_version }}'!"
    when:
      - "borg_version != borg.version"
